drop table if exists token cascade;
drop table if exists world cascade;
drop table if exists "user" cascade;
drop type if exists world_type;

create type world_type as enum ('DEFAULT', 'SUPERFLAT');

CREATE TABLE "user" (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	username VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
	active BOOLEAN NOT NULL
);
ALTER TABLE "user" ADD CONSTRAINT pk_user PRIMARY KEY (id);
ALTER TABLE "user" ADD CONSTRAINT uk_user_username UNIQUE (username);

create table token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token text not null,
    id_user bigint not null,
    is_expired boolean not null
);

alter table token add constraint pk_token primary key (id);
alter table token add constraint fk_token_id_user foreign key (id_user) references "user";

create table world (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    world_name varchar(20) not null,
    world_type world_type not null,
    world_image text not null,
    world_created_date timestamp not null,
    id_user bigint not null
);

alter table world add constraint pk_game primary key (id);
alter table world add constraint fk_game_id_user foreign key (id_user) references "user";