export { Loading } from "./Loading/Loading"
export { DeleteModal } from "./ConfigGame/deleteModal/DeleteModal"
export { EnterWorldModal } from "./ConfigGame/enterWorld/EnterWorldModal"
export { Notification } from "./Notification/Notification"
export { LoginRegister } from "./LoginRegister/LoginRegister"
export { ConfigGame } from "./ConfigGame/ConfigGame"
export { Home } from "./page/Home"
export { Button } from "./Button/Button"